# Generated by Django 4.2.2 on 2023-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='company_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
